# ===================================================================
# Spring Boot configuration for the "dev" profile.
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  # Database configure
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prime_user_db?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # Redis configure
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

  # JWT configure
  security:
    jwt.key:
      store: jwt.jks
      store-password: ${JWT_STORE_PASSWORD}
      pair-alias: ${JWT_PAIR_ALIAS}
      pair-password: ${JWT_PAIR_PASSWORD}